### PR TITLE
fix(antigravity): repair broken OAuth authentication - remove API key fallback

### LINKED ISSUE #798: [Bug/错误]: Antigravity渠道无法使用
### Pre-submission Checklist / 提交前检查

- [x] I have searched the [existing issues](https://github.com/looplj/axonhub/issues) and this bug has not been reported / 我已搜索现有 issues，此 Bug 尚未被报告
- [x] I have read the [documentation](https://github.com/looplj/axonhub#readme) / 我已阅读文档
- [x] I am using the latest version of AxonHub / 我正在使用 AxonHub 的最新版本

### Bug Description / Bug 描述

Antigravity渠道报“API keys are not supported by this API. Expected OAuth2 access token or other authentication credentials that assert a principal. See https://cloud.google.com/docs/authentication”

### Steps to Reproduce / 复现步骤

Antigravity渠道点测试

### Expected Behavior / 期望行为

测试成功

### Actual Behavior / 实际行为

渠道测试失败：API keys are not supported by this API. Expected OAuth2 access token or other authentication credentials that assert a principal. See https://cloud.google.com/docs/authentication

### Operating System / 操作系统

Docker / Docker

### AxonHub Version / AxonHub 版本

v0.9.4

### Usage Scenario / 使用场景

Other / 其他

### API Format / API 格式

Google Gemini - GenerateContent / Google Gemini GenerateContent

### Channel Type / 渠道类型

Google Gemini / Google Gemini

### Logs / 日志

```shell
{"level":"WARN","time":"2026-02-08T14:09:05Z","logger":"axonhub","message":"failed to get oauth token, attempting fallback to api key","error":"POST - https://oauth2.googleapis.com/token with status 400 Bad Request","context_deadline":"2026-02-08T14:09:33Z","trace_id":"at-8b9a5f8f-59bf-4a1f-9610-b32c795b654d","request_id":"ar-2425b0e5-f031-4693-81fc-317353f9bf2a","operation_name":"TestChannel"}
{"level":"WARN","time":"2026-02-08T14:09:07Z","logger":"axonhub","message":"antigravity request failed with network error","endpoint":"https://daily-cloudcode-pa.sandbox.googleapis.com","error":"POST - https://daily-cloudcode-pa.sandbox.googleapis.com/v1internal:generateContent with status 401 Unauthorized","context_deadline":"2026-02-08T14:09:33Z","trace_id":"at-8b9a5f8f-59bf-4a1f-9610-b32c795b654d","request_id":"ar-2425b0e5-f031-4693-81fc-317353f9bf2a","operation_name":"TestChannel"}
{"level":"WARN","time":"2026-02-08T14:09:07Z","logger":"axonhub","message":"request process failed","error":"POST - https://daily-cloudcode-pa.sandbox.googleapis.com/v1internal:generateContent with status 401 Unauthorized","channel_id":28,"channel_name":"Antigravity","model_id":"gemini-2.5-flash-lite","context_deadline":"2026-02-08T14:09:33Z","trace_id":"at-8b9a5f8f-59bf-4a1f-9610-b32c795b654d","request_id":"ar-2425b0e5-f031-4693-81fc-317353f9bf2a","operation_name":"TestChannel"}
{"level":"WARN","time":"2026-02-08T14:09:07Z","logger":"axonhub","message":"model turn to half-open due to consecutive failures","channel_id":28,"model_id":"","failures":3,"context_deadline":"2026-02-08T14:09:33Z","trace_id":"at-8b9a5f8f-59bf-4a1f-9610-b32c795b654d","request_id":"ar-2425b0e5-f031-4693-81fc-317353f9bf2a","operation_name":"TestChannel"}
{"level":"WARN","time":"2026-02-08T14:09:38Z","logger":"axonhub","message":"failed to auto refresh token","error":"POST - https://oauth2.googleapis.com/token with status 400 Bad Request"}
{"level":"WARN","time":"2026-02-08T14:10:38Z","logger":"axonhub","message":"failed to auto refresh token","error":"POST - https://oauth2.googleapis.com/token with status 400 Bad Request"}
```

### Additional Context / 其他补充信息

_No response_

### PR DESCRIPTION
**Pull request by djdembeck**
## Problem

Antigravity OAuth authentication was completely broken, manifesting as:

> \"Channel test failed: API keys are not supported by this API. Expected OAuth2 access token...\"

**Root cause: Two bugs working together:**

1. **API key fallback** (lines 221-238 in `transformer.go`) - Google now rejects all API key auth, making this fallback actively harmful
2. **Token refresh broke credential format** - The most critical bug. When OAuth tokens refreshed, `refreshToken|projectID` was converted to JSON, breaking all subsequent API calls

## Bug Origin

The credential format bug was introduced in commit `d5f3fd48` (Jan 29, 2026) when Antigravity was first added. The `refreshOAuthTokenFunc` was copied from Codex/Claude Code (which use JSON credentials) without adapting it for Antigravity's pipe-delimited format. This meant:
- Initial auth worked (correct format)
- First token refresh (~1 hour later) converted to JSON
- All subsequent calls failed

## Reference Implementation

Validated against **OpenCode Antigravity Auth Plugin (v1.5.0-1.5.1)** - uses OAuth-only with no API key fallback and `ideType: ANTIGRAVITY`.

### 1. Preserve Pipe-Delimited Format on Token Refresh (f4aa9fc2) ⭐ Critical
**Files:** `internal/server/biz/channel_llm.go`, `llm/oauth/token_provider.go`

```go
// BEFORE: Always JSON (broken for Antigravity)
updated.APIKey = credJSON

// AFTER: Preserve pipe format for Antigravity
if ch.Type == channel.TypeAntigravity {
    projectID := extractProjectIDFromAntigravityCreds(ch.Credentials.APIKey)
    updated.APIKey = fmt.Sprintf("%s|%s", refreshed.RefreshToken, projectID)
} else {
    updated.APIKey = credJSON  // JSON for other providers
}
```

### 2. Remove API Key Fallback (534f5ea6)
**File:** `llm/transformer/antigravity/transformer.go`

- Removed API key fallback logic (Google rejects it entirely)
- OAuth failure now returns clear error instead of broken fallback

### 3. Update ideType to ANTIGRAVITY (d243c378)
**Files:** `llm/transformer/antigravity/constants.go`, `internal/server/api/antigravity.go`

- Changed from `IDE_UNSPECIFIED` to `ANTIGRAVITY`
- Aligns with OpenCode plugin v1.5.1 spec

### 4. Update Tests (8f1a19a0)
**File:** `llm/transformer/antigravity/transformer_test.go`

- Added `TestOAuthFailureNoFallback`, `TestNoAPIKeyAuthConfig`, `TestOAuthOnlyHeaders`
- Verifies no API key headers sent, proper OAuth-only behavior

## Verification

```bash
cd llm && go test ./transformer/antigravity/...
ok  	github.com/looplj/axonhub/llm/transformer/antigravity	0.269s
# 38/38 tests pass
```

✅ Token refresh preserves `refreshToken|projectID` format  
✅ No API key fallback logic remains  
✅ `X-Goog-Api-Key` header never sent  
✅ `ideType` is `ANTIGRAVITY`  

## Related Issues

- Closes #798 - Antigravity渠道无法使用 (Antigravity channel cannot be used)

## Breaking Changes

None. The API key fallback was already non-functional (Google rejects API keys). Existing OAuth channels continue to work.

## Related Commits

- `c4dcc62f` (Jan 19) - Auto OAuth refresh added for Codex/Claude Code (JSON format)
- `d5f3fd48` (Jan 29) - **Bug introduced:** Antigravity added with pipe format but using JSON refresh function
- `534f5ea6`, `d243c378`, `8f1a19a0`, `f4aa9fc2` - This PR: Fix OAuth-only auth and pipe format preservation

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved error handling for OAuth token refresh with clearer HTTP error context
  * Fixed Antigravity channel token refresh to preserve project context

* **Improvements**
  * Enforced OAuth-only authentication for Antigravity integrations (removed API-key fallback)
  * Standardized routing paths to use trailing slashes for consistent navigation
  * Ensured build reliability by adjusting backend module resolution

* **Tests**
  * Added tests covering OAuth success/failure and header/auth behavior

### CODE REVIEW

File: llm/transformer/antigravity/transformer.go [hunk 1]
```diff
@@ -210,31 +210,15 @@ func (t *Transformer) TransformRequest(ctx context.Context, llmReq *llm.Request)
...
-	} else if t.config.APIKey != "" {
-		// Fallback to API Key if no token provider (legacy/testing?)
-		auth = &httpclient.AuthConfig{
-			Type:      "api_key",
-			APIKey:    t.config.APIKey,
-			HeaderKey: "x-goog-api-key",
+		if err != nil {
+			return nil, fmt.Errorf("failed to get OAuth token: %w", err)
 		}
+		headers.Set("Authorization", "Bearer "+creds.AccessToken)
```
Comment (looplj) [inline llm/transformer/antigravity/transformer.go]: We should use the unified httpclient.AuthConfig, we can set the type to  bearer

Comment (djdembeck) [reply llm/transformer/antigravity/transformer.go]: Done!
